# spring.application.name=Storage
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: gabriel
    password:
  h2:
    console:
      enabled: true

  jpa:
    database-plataform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    show-sql: true
  flyway:
    enabled: true
